### ISSUE TITLE
No able to run the flow alongside with evaluation - run_id cannot be found

### ISSUE THREAD

**Issue by GeisaFaustino** [microsoft/mlops-promptflow-prompt#20]
No able to run the flow alongside with evaluation using the command `python -m mlops.local_prompt_eval --config_name named_entity_recognition --environment_name pr --run_id <run_id>`  as provided in [doc](https://github.com/microsoft/mlops-promptflow-prompt#local-execution). I am using the `run_id` provided in the previous step. Please see the screenshot below for details.

![image](https://github.com/microsoft/mlops-promptflow-prompt/assets/32823639/9b857559-5ad2-4188-bf67-e353bef7c2ac)

I also tried running it using the a `run_id` from a json file of flow artifacts folder generated on previous step.
![image](https://github.com/microsoft/mlops-promptflow-prompt/assets/32823639/749780dc-b476-4c0a-ba49-4e7119668287)

**Comment by sbaidachni** [comment]
@GeisaFaustino In order to run evaluation you need a run id from a batch execution. Please, use mlops.local_prompt_pipeline rather than mlops.local_prompt_test. The mlops.local_prompt_pipeline_test is just a script to test everything on a single default raw - prompt flow doesn't create a real run for that. We will adjust the documentation to note about it.

**Comment by anastasiyagromova** [comment]
@GeisaFaustino the run_id is fixed in the following PR. Feel free to test on your end. Will close for now. 
https://github.com/microsoft/mlops-promptflow-prompt/pull/27/files
